# ----------------------------------------------------------------------------
# (C) Copyright IBM Corp. 2016, 2020
#
# SPDX-License-Identifier: Apache-2.0
# ----------------------------------------------------------------------------

FROM openliberty/open-liberty:19.0.0.12-full-java8-openj9-ubi as base

ENV LICENSE accept

USER root
RUN \
  yum update -y && \
  yum install -y unzip nmap-ncat && \
  yum -y clean all

USER 1001
COPY volumes/dist /dist
COPY volumes/scripts  /scripts
RUN unzip -qq /dist/fhir-server-distribution.zip -d /tmp && \
    /tmp/fhir-server-dist/install-fhir.sh /opt/ol/wlp && \
    rm -fr /opt/ol/wlp/usr/servers/fhir-server/config/* && \
    cp -pr /dist/config/* /opt/ol/wlp/usr/servers/fhir-server/config/ && \
    cp -pr /dist/userlib/* /opt/ol/wlp/usr/servers/fhir-server/userlib/


FROM openliberty/open-liberty:19.0.0.12-full-java8-openj9-ubi
COPY --chown=1001:0 --from=base /opt/ol/wlp/ /opt/ol/wlp

MAINTAINER Lee Surprenant <lmsurpre@us.ibm.com>

ENV FHIR /opt/ol/wlp/usr/servers/fhir-server

# Set the working directory to the fhir-server liberty server
WORKDIR ${FHIR}

# Set the output directory so that output will appear under the working directory
ENV WLP_OUTPUT_DIR=/opt/ol/wlp/usr/servers

# Tell liberty not to worry about a keystore since we provide our own at a different path
ENV KEYSTORE_REQUIRED "false"

# Replace links to defaultServer with links to fhir-server
USER root
RUN ln -sfn ${FHIR} /output && \
    ln -sfn ${FHIR} /config && \
    rm -rf /opt/ol/wlp/output && \
    rm -rf /opt/ol/wlp/usr/servers/defaultServer

USER 1001
RUN ls -l /config/* && mkdir -p /config/configDropins/defaults/
CMD ["/opt/ol/wlp/bin/server", "run", "fhir-server"]
