# ----------------------------------------------------------------------------
# (C) Copyright IBM Corp. 2017,2018,2019
# 
# SPDX-License-Identifier: Apache-2.0
# ----------------------------------------------------------------------------

FROM fhir-baseos:latest

LABEL maintainer Phil Adams <phil_adams@us.ibm.com>

ENV LICENSE accept

COPY volumes/dist /dist
COPY volumes/scripts  /scripts

RUN \
  useradd fhir && \
  cp /scripts/.bash_profile /home/fhir/.bash_profile && \
  chown fhir /home/fhir/.bash_profile && \
  mkdir /opt/ibm && \
  chmod 777 /opt/ibm && \
  su - fhir -c '/scripts/deploy-fhir.sh'

CMD su - fhir -c '/opt/ibm/fhir-server/wlp/bin/server run fhir-server'

