# ----------------------------------------------------------------------------
# (C) Copyright IBM Corp. 2017,2018,2019
# 
# SPDX-License-Identifier: Apache-2.0
# ----------------------------------------------------------------------------

FROM fhir-baseos:latest

LABEL maintainer Phil Adams <phil_adams@us.ibm.com>

ENV LICENSE accept

COPY volumes/dist /dist
COPY volumes/scripts  /scripts

RUN \
  useradd fhir && \
  cp -pr /scripts /home/fhir && mv /home/fhir/scripts/.bash_profile /home/fhir && chown fhir:fhir /home/fhir/.bash_profile && \
  chown fhir:fhir /home/fhir/scripts && chown fhir:fhir /home/fhir/scripts/* && chmod 755 /home/fhir/scripts && chmod 755 /home/fhir/scripts/* && \
  mkdir /opt/ibm && chmod 777 /opt/ibm && \
  su - fhir -c '/home/fhir/scripts/deploy-fhir.sh'

CMD su - fhir -c '/opt/ibm/fhir-server/wlp/bin/server run fhir-server'

