/**
 * (C) Copyright IBM Corp. 2019
 *
 * SPDX-License-Identifier: Apache-2.0
 */

package com.ibm.watsonhealth.fhir.model.path;

import java.util.HashMap;
import java.util.Map;

public enum FHIRPathType {
    // FHIR types
    FHIR_ANY("FHIR", "Any"),
    FHIR_RESOURCE("FHIR", "Resource", FHIR_ANY),
    FHIR_DOMAIN_RESOURCE("FHIR", "DomainResource", FHIR_RESOURCE),
    FHIR_ELEMENT("FHIR", "Element", FHIR_ANY),
    FHIR_BACKBONE_ELEMENT("FHIR", "BackboneElement", FHIR_ELEMENT),
    FHIR_ADDRESS("FHIR", "Address", FHIR_ELEMENT),
    FHIR_AGE("FHIR", "Age", FHIR_ELEMENT),
    FHIR_ANNOTATION("FHIR", "Annotation", FHIR_ELEMENT),
    FHIR_ATTACHMENT("FHIR", "Attachment", FHIR_ELEMENT),
    FHIR_CODEABLE_CONCEPT("FHIR", "CodeableConcept", FHIR_ELEMENT),
    FHIR_CODING("FHIR", "Coding", FHIR_ELEMENT),
    FHIR_CONTACT_DETAIL("FHIR", "ContactDetail", FHIR_ELEMENT),
    FHIR_CONTACT_POINT("FHIR", "ContactPoint", FHIR_ELEMENT),
    FHIR_CONTRIBUTOR("FHIR", "Contributor", FHIR_ELEMENT),
    FHIR_COUNT("FHIR", "Count", FHIR_ELEMENT),
    FHIR_DATA_REQUIREMENT("FHIR", "DataRequirement", FHIR_ELEMENT),
    FHIR_DISTANCE("FHIR", "Distance", FHIR_ELEMENT),
    FHIR_DOSAGE("FHIR", "Dosage", FHIR_BACKBONE_ELEMENT),
    FHIR_DURATION("FHIR", "Duration", FHIR_ELEMENT),
    FHIR_ELEMENT_DEFINITION("FHIR", "ElementDefinition", FHIR_BACKBONE_ELEMENT),
    FHIR_EXPRESSION("FHIR", "Expression", FHIR_ELEMENT),
    FHIR_EXTENSION("FHIR", "Extension", FHIR_ELEMENT),
    FHIR_HUMAN_NAME("FHIR", "HumanName", FHIR_ELEMENT),
    FHIR_IDENTIFIER("FHIR", "Identifier", FHIR_ELEMENT),
    FHIR_MARKETING_STATUS("FHIR", "MarketingStatus", FHIR_BACKBONE_ELEMENT),
    FHIR_META("FHIR", "Meta", FHIR_ELEMENT),
    FHIR_MONEY("FHIR", "Money", FHIR_ELEMENT),
    FHIR_MONEY_QUANTITY("FHIR", "MoneyQuantity", FHIR_ELEMENT),
    FHIR_NARRATIVE("FHIR", "Narrative", FHIR_ELEMENT),
    FHIR_PARAMETER_DEFINITION("FHIR", "ParameterDefinition", FHIR_ELEMENT),
    FHIR_PERIOD("FHIR", "Period", FHIR_ELEMENT),
    FHIR_POPULATION("FHIR", "Population", FHIR_BACKBONE_ELEMENT),
    FHIR_PROD_CHARACTERISTIC("FHIR", "ProdCharacteristic", FHIR_BACKBONE_ELEMENT),
    FHIR_PRODUCT_SHELF_LIFE("FHIR", "ProductShelfLife", FHIR_BACKBONE_ELEMENT),
    FHIR_QUANTITY("FHIR", "Quantity", FHIR_ELEMENT),
    FHIR_RANGE("FHIR", "Range", FHIR_ELEMENT),
    FHIR_RATIO("FHIR", "Ratio", FHIR_ELEMENT),
    FHIR_REFERENCE("FHIR", "Reference", FHIR_ELEMENT),
    FHIR_RELATED_ARTIFACT("FHIR", "RelatedArtifact", FHIR_ELEMENT),
    FHIR_SAMPLED_DATA("FHIR", "SampledData", FHIR_ELEMENT),
    FHIR_SIGNATURE("FHIR", "Signature", FHIR_ELEMENT),
    FHIR_SIMPLE_QUANTITY("FHIR", "SimpleQuantity", FHIR_ELEMENT),
    FHIR_SUBSTANCE_AMOUNT("FHIR", "SubstanceAmount", FHIR_BACKBONE_ELEMENT),
    FHIR_TIMING("FHIR", "Timing", FHIR_BACKBONE_ELEMENT),
    FHIR_TRIGGER_DEFINITION("FHIR", "TriggerDefinition", FHIR_ELEMENT),
    FHIR_USAGE_CONTEXT("FHIR", "UsageContext", FHIR_ELEMENT),
    FHIR_BASE64BINARY("FHIR", "base64Binary", FHIR_ELEMENT),
    FHIR_BOOLEAN("FHIR", "boolean", FHIR_ELEMENT),
    FHIR_CANONICAL("FHIR", "canonical", FHIR_ELEMENT),
    FHIR_CODE("FHIR", "code", FHIR_ELEMENT),
    FHIR_DATE("FHIR", "date", FHIR_ELEMENT),
    FHIR_DATE_TIME("FHIR", "dateTime", FHIR_ELEMENT),
    FHIR_DECIMAL("FHIR", "decimal", FHIR_ELEMENT),
    FHIR_ID("FHIR", "id", FHIR_ELEMENT),
    FHIR_INSTANT("FHIR", "instant", FHIR_ELEMENT),
    FHIR_INTEGER("FHIR", "integer", FHIR_ELEMENT),
    FHIR_MARKDOWN("FHIR", "markdown", FHIR_ELEMENT),
    FHIR_OID("FHIR", "oid", FHIR_ELEMENT),
    FHIR_POSITIVE_INT("FHIR", "positiveInt", FHIR_ELEMENT),
    FHIR_STRING("FHIR", "string", FHIR_ELEMENT),
    FHIR_TIME("FHIR", "time", FHIR_ELEMENT),
    FHIR_UNSIGNED_INT("FHIR", "unsignedInt", FHIR_ELEMENT),
    FHIR_URI("FHIR", "uri", FHIR_ELEMENT),
    FHIR_URL("FHIR", "url", FHIR_ELEMENT),
    FHIR_UUID("FHIR", "uuid", FHIR_ELEMENT),
    FHIR_XHTML("FHIR", "xhtml"),
    FHIR_ACCOUNT("FHIR", "Account", FHIR_DOMAIN_RESOURCE),
    FHIR_ACTIVITY_DEFINITION("FHIR", "ActivityDefinition", FHIR_DOMAIN_RESOURCE),
    FHIR_ADVERSE_EVENT("FHIR", "AdverseEvent", FHIR_DOMAIN_RESOURCE),
    FHIR_ALLERGY_INTOLERANCE("FHIR", "AllergyIntolerance", FHIR_DOMAIN_RESOURCE),
    FHIR_APPOINTMENT("FHIR", "Appointment", FHIR_DOMAIN_RESOURCE),
    FHIR_APPOINTMENT_RESPONSE("FHIR", "AppointmentResponse", FHIR_DOMAIN_RESOURCE),
    FHIR_AUDIT_EVENT("FHIR", "AuditEvent", FHIR_DOMAIN_RESOURCE),
    FHIR_BASIC("FHIR", "Basic", FHIR_DOMAIN_RESOURCE),
    FHIR_BINARY("FHIR", "Binary", FHIR_RESOURCE),
    FHIR_BIOLOGICALLY_DERIVED_PRODUCT("FHIR", "BiologicallyDerivedProduct", FHIR_DOMAIN_RESOURCE),
    FHIR_BODY_STRUCTURE("FHIR", "BodyStructure", FHIR_DOMAIN_RESOURCE),
    FHIR_BUNDLE("FHIR", "Bundle", FHIR_RESOURCE),
    FHIR_CAPABILITY_STATEMENT("FHIR", "CapabilityStatement", FHIR_DOMAIN_RESOURCE),
    FHIR_CARE_PLAN("FHIR", "CarePlan", FHIR_DOMAIN_RESOURCE),
    FHIR_CARE_TEAM("FHIR", "CareTeam", FHIR_DOMAIN_RESOURCE),
    FHIR_CATALOG_ENTRY("FHIR", "CatalogEntry", FHIR_DOMAIN_RESOURCE),
    FHIR_CHARGE_ITEM("FHIR", "ChargeItem", FHIR_DOMAIN_RESOURCE),
    FHIR_CHARGE_ITEM_DEFINITION("FHIR", "ChargeItemDefinition", FHIR_DOMAIN_RESOURCE),
    FHIR_CLAIM("FHIR", "Claim", FHIR_DOMAIN_RESOURCE),
    FHIR_CLAIM_RESPONSE("FHIR", "ClaimResponse", FHIR_DOMAIN_RESOURCE),
    FHIR_CLINICAL_IMPRESSION("FHIR", "ClinicalImpression", FHIR_DOMAIN_RESOURCE),
    FHIR_CODE_SYSTEM("FHIR", "CodeSystem", FHIR_DOMAIN_RESOURCE),
    FHIR_COMMUNICATION("FHIR", "Communication", FHIR_DOMAIN_RESOURCE),
    FHIR_COMMUNICATION_REQUEST("FHIR", "CommunicationRequest", FHIR_DOMAIN_RESOURCE),
    FHIR_COMPARTMENT_DEFINITION("FHIR", "CompartmentDefinition", FHIR_DOMAIN_RESOURCE),
    FHIR_COMPOSITION("FHIR", "Composition", FHIR_DOMAIN_RESOURCE),
    FHIR_CONCEPT_MAP("FHIR", "ConceptMap", FHIR_DOMAIN_RESOURCE),
    FHIR_CONDITION("FHIR", "Condition", FHIR_DOMAIN_RESOURCE),
    FHIR_CONSENT("FHIR", "Consent", FHIR_DOMAIN_RESOURCE),
    FHIR_CONTRACT("FHIR", "Contract", FHIR_DOMAIN_RESOURCE),
    FHIR_COVERAGE("FHIR", "Coverage", FHIR_DOMAIN_RESOURCE),
    FHIR_COVERAGE_ELIGIBILITY_REQUEST("FHIR", "CoverageEligibilityRequest", FHIR_DOMAIN_RESOURCE),
    FHIR_COVERAGE_ELIGIBILITY_RESPONSE("FHIR", "CoverageEligibilityResponse", FHIR_DOMAIN_RESOURCE),
    FHIR_DETECTED_ISSUE("FHIR", "DetectedIssue", FHIR_DOMAIN_RESOURCE),
    FHIR_DEVICE("FHIR", "Device", FHIR_DOMAIN_RESOURCE),
    FHIR_DEVICE_DEFINITION("FHIR", "DeviceDefinition", FHIR_DOMAIN_RESOURCE),
    FHIR_DEVICE_METRIC("FHIR", "DeviceMetric", FHIR_DOMAIN_RESOURCE),
    FHIR_DEVICE_REQUEST("FHIR", "DeviceRequest", FHIR_DOMAIN_RESOURCE),
    FHIR_DEVICE_USE_STATEMENT("FHIR", "DeviceUseStatement", FHIR_DOMAIN_RESOURCE),
    FHIR_DIAGNOSTIC_REPORT("FHIR", "DiagnosticReport", FHIR_DOMAIN_RESOURCE),
    FHIR_DOCUMENT_MANIFEST("FHIR", "DocumentManifest", FHIR_DOMAIN_RESOURCE),
    FHIR_DOCUMENT_REFERENCE("FHIR", "DocumentReference", FHIR_DOMAIN_RESOURCE),
    FHIR_EFFECT_EVIDENCE_SYNTHESIS("FHIR", "EffectEvidenceSynthesis", FHIR_DOMAIN_RESOURCE),
    FHIR_ENCOUNTER("FHIR", "Encounter", FHIR_DOMAIN_RESOURCE),
    FHIR_ENDPOINT("FHIR", "Endpoint", FHIR_DOMAIN_RESOURCE),
    FHIR_ENROLLMENT_REQUEST("FHIR", "EnrollmentRequest", FHIR_DOMAIN_RESOURCE),
    FHIR_ENROLLMENT_RESPONSE("FHIR", "EnrollmentResponse", FHIR_DOMAIN_RESOURCE),
    FHIR_EPISODE_OF_CARE("FHIR", "EpisodeOfCare", FHIR_DOMAIN_RESOURCE),
    FHIR_EVENT_DEFINITION("FHIR", "EventDefinition", FHIR_DOMAIN_RESOURCE),
    FHIR_EVIDENCE("FHIR", "Evidence", FHIR_DOMAIN_RESOURCE),
    FHIR_EVIDENCE_VARIABLE("FHIR", "EvidenceVariable", FHIR_DOMAIN_RESOURCE),
    FHIR_EXAMPLE_SCENARIO("FHIR", "ExampleScenario", FHIR_DOMAIN_RESOURCE),
    FHIR_EXPLANATION_OF_BENEFIT("FHIR", "ExplanationOfBenefit", FHIR_DOMAIN_RESOURCE),
    FHIR_FAMILY_MEMBER_HISTORY("FHIR", "FamilyMemberHistory", FHIR_DOMAIN_RESOURCE),
    FHIR_FLAG("FHIR", "Flag", FHIR_DOMAIN_RESOURCE),
    FHIR_GOAL("FHIR", "Goal", FHIR_DOMAIN_RESOURCE),
    FHIR_GRAPH_DEFINITION("FHIR", "GraphDefinition", FHIR_DOMAIN_RESOURCE),
    FHIR_GROUP("FHIR", "Group", FHIR_DOMAIN_RESOURCE),
    FHIR_GUIDANCE_RESPONSE("FHIR", "GuidanceResponse", FHIR_DOMAIN_RESOURCE),
    FHIR_HEALTHCARE_SERVICE("FHIR", "HealthcareService", FHIR_DOMAIN_RESOURCE),
    FHIR_IMAGING_STUDY("FHIR", "ImagingStudy", FHIR_DOMAIN_RESOURCE),
    FHIR_IMMUNIZATION("FHIR", "Immunization", FHIR_DOMAIN_RESOURCE),
    FHIR_IMMUNIZATION_EVALUATION("FHIR", "ImmunizationEvaluation", FHIR_DOMAIN_RESOURCE),
    FHIR_IMMUNIZATION_RECOMMENDATION("FHIR", "ImmunizationRecommendation", FHIR_DOMAIN_RESOURCE),
    FHIR_IMPLEMENTATION_GUIDE("FHIR", "ImplementationGuide", FHIR_DOMAIN_RESOURCE),
    FHIR_INSURANCE_PLAN("FHIR", "InsurancePlan", FHIR_DOMAIN_RESOURCE),
    FHIR_INVOICE("FHIR", "Invoice", FHIR_DOMAIN_RESOURCE),
    FHIR_LIBRARY("FHIR", "Library", FHIR_DOMAIN_RESOURCE),
    FHIR_LINKAGE("FHIR", "Linkage", FHIR_DOMAIN_RESOURCE),
    FHIR_LIST("FHIR", "List", FHIR_DOMAIN_RESOURCE),
    FHIR_LOCATION("FHIR", "Location", FHIR_DOMAIN_RESOURCE),
    FHIR_MEASURE("FHIR", "Measure", FHIR_DOMAIN_RESOURCE),
    FHIR_MEASURE_REPORT("FHIR", "MeasureReport", FHIR_DOMAIN_RESOURCE),
    FHIR_MEDIA("FHIR", "Media", FHIR_DOMAIN_RESOURCE),
    FHIR_MEDICATION("FHIR", "Medication", FHIR_DOMAIN_RESOURCE),
    FHIR_MEDICATION_ADMINISTRATION("FHIR", "MedicationAdministration", FHIR_DOMAIN_RESOURCE),
    FHIR_MEDICATION_DISPENSE("FHIR", "MedicationDispense", FHIR_DOMAIN_RESOURCE),
    FHIR_MEDICATION_KNOWLEDGE("FHIR", "MedicationKnowledge", FHIR_DOMAIN_RESOURCE),
    FHIR_MEDICATION_REQUEST("FHIR", "MedicationRequest", FHIR_DOMAIN_RESOURCE),
    FHIR_MEDICATION_STATEMENT("FHIR", "MedicationStatement", FHIR_DOMAIN_RESOURCE),
    FHIR_MEDICINAL_PRODUCT("FHIR", "MedicinalProduct", FHIR_DOMAIN_RESOURCE),
    FHIR_MEDICINAL_PRODUCT_AUTHORIZATION("FHIR", "MedicinalProductAuthorization", FHIR_DOMAIN_RESOURCE),
    FHIR_MEDICINAL_PRODUCT_CONTRAINDICATION("FHIR", "MedicinalProductContraindication", FHIR_DOMAIN_RESOURCE),
    FHIR_MEDICINAL_PRODUCT_INDICATION("FHIR", "MedicinalProductIndication", FHIR_DOMAIN_RESOURCE),
    FHIR_MEDICINAL_PRODUCT_INGREDIENT("FHIR", "MedicinalProductIngredient", FHIR_DOMAIN_RESOURCE),
    FHIR_MEDICINAL_PRODUCT_INTERACTION("FHIR", "MedicinalProductInteraction", FHIR_DOMAIN_RESOURCE),
    FHIR_MEDICINAL_PRODUCT_MANUFACTURED("FHIR", "MedicinalProductManufactured", FHIR_DOMAIN_RESOURCE),
    FHIR_MEDICINAL_PRODUCT_PACKAGED("FHIR", "MedicinalProductPackaged", FHIR_DOMAIN_RESOURCE),
    FHIR_MEDICINAL_PRODUCT_PHARMACEUTICAL("FHIR", "MedicinalProductPharmaceutical", FHIR_DOMAIN_RESOURCE),
    FHIR_MEDICINAL_PRODUCT_UNDESIRABLE_EFFECT("FHIR", "MedicinalProductUndesirableEffect", FHIR_DOMAIN_RESOURCE),
    FHIR_MESSAGE_DEFINITION("FHIR", "MessageDefinition", FHIR_DOMAIN_RESOURCE),
    FHIR_MESSAGE_HEADER("FHIR", "MessageHeader", FHIR_DOMAIN_RESOURCE),
    FHIR_MOLECULAR_SEQUENCE("FHIR", "MolecularSequence", FHIR_DOMAIN_RESOURCE),
    FHIR_NAMING_SYSTEM("FHIR", "NamingSystem", FHIR_DOMAIN_RESOURCE),
    FHIR_NUTRITION_ORDER("FHIR", "NutritionOrder", FHIR_DOMAIN_RESOURCE),
    FHIR_OBSERVATION("FHIR", "Observation", FHIR_DOMAIN_RESOURCE),
    FHIR_OBSERVATION_DEFINITION("FHIR", "ObservationDefinition", FHIR_DOMAIN_RESOURCE),
    FHIR_OPERATION_DEFINITION("FHIR", "OperationDefinition", FHIR_DOMAIN_RESOURCE),
    FHIR_OPERATION_OUTCOME("FHIR", "OperationOutcome", FHIR_DOMAIN_RESOURCE),
    FHIR_ORGANIZATION("FHIR", "Organization", FHIR_DOMAIN_RESOURCE),
    FHIR_ORGANIZATION_AFFILIATION("FHIR", "OrganizationAffiliation", FHIR_DOMAIN_RESOURCE),
    FHIR_PARAMETERS("FHIR", "Parameters", FHIR_RESOURCE),
    FHIR_PATIENT("FHIR", "Patient", FHIR_DOMAIN_RESOURCE),
    FHIR_PAYMENT_NOTICE("FHIR", "PaymentNotice", FHIR_DOMAIN_RESOURCE),
    FHIR_PAYMENT_RECONCILIATION("FHIR", "PaymentReconciliation", FHIR_DOMAIN_RESOURCE),
    FHIR_PERSON("FHIR", "Person", FHIR_DOMAIN_RESOURCE),
    FHIR_PLAN_DEFINITION("FHIR", "PlanDefinition", FHIR_DOMAIN_RESOURCE),
    FHIR_PRACTITIONER("FHIR", "Practitioner", FHIR_DOMAIN_RESOURCE),
    FHIR_PRACTITIONER_ROLE("FHIR", "PractitionerRole", FHIR_DOMAIN_RESOURCE),
    FHIR_PROCEDURE("FHIR", "Procedure", FHIR_DOMAIN_RESOURCE),
    FHIR_PROVENANCE("FHIR", "Provenance", FHIR_DOMAIN_RESOURCE),
    FHIR_QUESTIONNAIRE("FHIR", "Questionnaire", FHIR_DOMAIN_RESOURCE),
    FHIR_QUESTIONNAIRE_RESPONSE("FHIR", "QuestionnaireResponse", FHIR_DOMAIN_RESOURCE),
    FHIR_RELATED_PERSON("FHIR", "RelatedPerson", FHIR_DOMAIN_RESOURCE),
    FHIR_REQUEST_GROUP("FHIR", "RequestGroup", FHIR_DOMAIN_RESOURCE),
    FHIR_RESEARCH_DEFINITION("FHIR", "ResearchDefinition", FHIR_DOMAIN_RESOURCE),
    FHIR_RESEARCH_ELEMENT_DEFINITION("FHIR", "ResearchElementDefinition", FHIR_DOMAIN_RESOURCE),
    FHIR_RESEARCH_STUDY("FHIR", "ResearchStudy", FHIR_DOMAIN_RESOURCE),
    FHIR_RESEARCH_SUBJECT("FHIR", "ResearchSubject", FHIR_DOMAIN_RESOURCE),
    FHIR_RISK_ASSESSMENT("FHIR", "RiskAssessment", FHIR_DOMAIN_RESOURCE),
    FHIR_RISK_EVIDENCE_SYNTHESIS("FHIR", "RiskEvidenceSynthesis", FHIR_DOMAIN_RESOURCE),
    FHIR_SCHEDULE("FHIR", "Schedule", FHIR_DOMAIN_RESOURCE),
    FHIR_SEARCH_PARAMETER("FHIR", "SearchParameter", FHIR_DOMAIN_RESOURCE),
    FHIR_SERVICE_REQUEST("FHIR", "ServiceRequest", FHIR_DOMAIN_RESOURCE),
    FHIR_SLOT("FHIR", "Slot", FHIR_DOMAIN_RESOURCE),
    FHIR_SPECIMEN("FHIR", "Specimen", FHIR_DOMAIN_RESOURCE),
    FHIR_SPECIMEN_DEFINITION("FHIR", "SpecimenDefinition", FHIR_DOMAIN_RESOURCE),
    FHIR_STRUCTURE_DEFINITION("FHIR", "StructureDefinition", FHIR_DOMAIN_RESOURCE),
    FHIR_STRUCTURE_MAP("FHIR", "StructureMap", FHIR_DOMAIN_RESOURCE),
    FHIR_SUBSCRIPTION("FHIR", "Subscription", FHIR_DOMAIN_RESOURCE),
    FHIR_SUBSTANCE("FHIR", "Substance", FHIR_DOMAIN_RESOURCE),
    FHIR_SUBSTANCE_NUCLEIC_ACID("FHIR", "SubstanceNucleicAcid", FHIR_DOMAIN_RESOURCE),
    FHIR_SUBSTANCE_POLYMER("FHIR", "SubstancePolymer", FHIR_DOMAIN_RESOURCE),
    FHIR_SUBSTANCE_PROTEIN("FHIR", "SubstanceProtein", FHIR_DOMAIN_RESOURCE),
    FHIR_SUBSTANCE_REFERENCE_INFORMATION("FHIR", "SubstanceReferenceInformation", FHIR_DOMAIN_RESOURCE),
    FHIR_SUBSTANCE_SOURCE_MATERIAL("FHIR", "SubstanceSourceMaterial", FHIR_DOMAIN_RESOURCE),
    FHIR_SUBSTANCE_SPECIFICATION("FHIR", "SubstanceSpecification", FHIR_DOMAIN_RESOURCE),
    FHIR_SUPPLY_DELIVERY("FHIR", "SupplyDelivery", FHIR_DOMAIN_RESOURCE),
    FHIR_SUPPLY_REQUEST("FHIR", "SupplyRequest", FHIR_DOMAIN_RESOURCE),
    FHIR_TASK("FHIR", "Task", FHIR_DOMAIN_RESOURCE),
    FHIR_TERMINOLOGY_CAPABILITIES("FHIR", "TerminologyCapabilities", FHIR_DOMAIN_RESOURCE),
    FHIR_TEST_REPORT("FHIR", "TestReport", FHIR_DOMAIN_RESOURCE),
    FHIR_TEST_SCRIPT("FHIR", "TestScript", FHIR_DOMAIN_RESOURCE),
    FHIR_VALUE_SET("FHIR", "ValueSet", FHIR_DOMAIN_RESOURCE),
    FHIR_VERIFICATION_RESULT("FHIR", "VerificationResult", FHIR_DOMAIN_RESOURCE),
    FHIR_VISION_PRESCRIPTION("FHIR", "VisionPrescription", FHIR_DOMAIN_RESOURCE),
    FHIR_TYPE("FHIR", "Type"),
    
    // FHIRPath system types
    SYSTEM_ANY("System", "Any"),
    SYSTEM_BOOLEAN("System", "Boolean", SYSTEM_ANY),
    SYSTEM_STRING("System", "String", SYSTEM_ANY),
    SYSTEM_INTEGER("System", "Integer", SYSTEM_ANY),
    SYSTEM_DECIMAL("System", "Decimal", SYSTEM_ANY),
    SYSTEM_DATE_TIME("System", "DateTime", SYSTEM_ANY),
    SYSTEM_TIME("System", "Time", SYSTEM_ANY);
    
    private final String namespace;
    private final String name;
    private final FHIRPathType superType;
    
    private static final Map<String, FHIRPathType> FHIR_PATH_TYPE_MAP = new HashMap<>();
    static {
        for (FHIRPathType type : FHIRPathType.values()) {
            FHIR_PATH_TYPE_MAP.put(type.namespace + "." + type.name, type);
        }
    }
    
    FHIRPathType(String namespace, String name) {
        this(namespace, name, null);
    }
    
    FHIRPathType(String namespace, String name, FHIRPathType superType) {
        this.namespace = namespace;
        this.name = name;
        this.superType = superType;
    }
    
    public String namespace() {
        return namespace;
    }
    
    public String getName() {
        return name;
    }
    
    public FHIRPathType superType() {
        return superType;
    }
    
    public boolean isAssignableFrom(FHIRPathType type) {
        if (type == null) {
            return false;
        }
        if (this == type) {
            return true;
        }
        if (this == SYSTEM_ANY && "System".equals(type.namespace)) {
            return true;
        }
        if (this == FHIR_ANY && "FHIR".equals(type.namespace)) {
            return true;
        }
        return isAssignableFrom(type.superType);
    }
    
    public static FHIRPathType from(String fullName) {
        return FHIR_PATH_TYPE_MAP.get(fullName);
    }
    
    public static FHIRPathType from(String namespace, String name) {
        return FHIR_PATH_TYPE_MAP.get(namespace + "." + name);
    }
    
    public static FHIRPathType from(Class<?> type) {
        return from("FHIR", type.getSimpleName());
    }
}
