/*
 * (C) Copyright IBM Corp. 2022
 *
 * SPDX-License-Identifier: Apache-2.0
 */
 
package com.ibm.fhir.persistence.jdbc.util;


/**
 * Metrics related to the persistence layer
 */
public enum FHIRPersistenceJDBCMetric {
    M_JDBC_EXTRACT_SEARCH_PARAMS,
    M_JDBC_ADD_ANY_RESOURCE,
    M_JDBC_INSERT_PARAMS,
    M_JDBC_CREATE,
    M_JDBC_UPDATE,
    M_JDBC_DELETE,
    M_JDBC_READ,
    M_JDBC_VREAD,
    M_JDBC_HISTORY,
    M_JDBC_SEARCH,
    M_JDBC_COMMIT,
    M_JDBC_FLUSH_TX_DATA,
    M_JDBC_RESOLVE_CODE_SYSTEMS,
    M_JDBC_RESOLVE_COMMON_TOKEN_VALUES,
    M_JDBC_RESOLVE_LOGICAL_RESOURCE_IDENT,
    M_JDBC_RESOLVE_CANONICAL_VALUES,
    M_JDBC_INSERT_TOKEN_REFS,
    M_JDBC_INSERT_REF_VALUES,
    M_JDBC_INSERT_TAGS,
    M_JDBC_INSERT_PROFILES,
    M_JDBC_INSERT_SECURITY,
    M_JDBC_UPSERT_COMMON_TOKEN_VALUES,
    M_JDBC_FETCH_NEW_COMMON_TOKEN_VALUES,
    M_JDBC_DELETE_RESOURCE_PARAMETERS,
    M_JDBC_AFTER_COMMIT
}
