{
 "title": "IBM Event Streams Performance Dashboard",
 "description": "Stats relating to the performance of Event Streams pods",
 "time": { "from": "now/d", "to": "now/d" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "namespace",
    "label": "Namespace",
    "query": "label_values(kube_pod_info, namespace)"
   },
   {
    "name": "kafka",
    "label": "Kafka",
    "query": "label_values(kafka_controller_kafkacontroller_controllerstate_value{kubernetes_namespace=~\"$namespace\"},  kafka)"
   },
   {
    "name": "proxy",
    "label": "Proxy",
    "query": "label_values(kube_pod_info{namespace=~\"$namespace\"}, pod)"
   },
   {
    "name": "collector",
    "label": "Collector",
    "query": "label_values(kube_pod_info{namespace=~\"$namespace\"}, pod)"
   },
   {
    "name": "accessController",
    "label": "Access-Controller",
    "query": "label_values(kube_pod_info{namespace=~\"$namespace\"}, pod)"
   }
  ]
 },
 "panels": [
  {
   "title": "Kafka Memory and CPU",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Total Memory Usage by $kafka",
     "type": "singlestat",
     "description": "The total memory being used inside Kafka pod $kafka. It is a sum of the memory in use by the containers inside the pod",
     "gridPos": { "h": 8, "w": 3, "x": 0, "y": 1 },
     "repeat": "kafka",
     "format": "bytes",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(container_memory_working_set_bytes{image!=\"\", namespace=~\"$namespace\", pod_name=~\".*-kafka-sts-$kafka\",container_name!=\"POD\"})"
      }
     ]
    },
    {
     "title": "Memory Usage by kafka $kafka",
     "type": "graph",
     "description": "Graph showing the memory usage and limits for each container in kafka pod $kafka",
     "gridPos": { "h": 8, "w": 9, "x": 3, "y": 1 },
     "repeat": "kafka",
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "avg by(container_name) (container_memory_working_set_bytes{image!=\"\", namespace=\"$namespace\", pod_name=~\".*-kafka-sts-$kafka\", container_name!=\"POD\"})",
       "legendFormat": "Current: {{ container_name }}"
      },
      {
       "expr": "kube_pod_container_resource_limits_memory_bytes{namespace=\"$namespace\", pod=~\".*-kafka-sts-$kafka\", container!=\"POD\"}",
       "legendFormat": "Limit: {{ container }}"
      }
     ]
    },
    {
     "title": "Total CPU for $kafka",
     "type": "singlestat",
     "description": "The total CPU in use by kafka pod $kafka. It is a sum of the CPU usage by the containers inside the pod",
     "gridPos": { "h": 8, "w": 2, "x": 12, "y": 1 },
     "repeat": "kafka",
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(rate(container_cpu_usage_seconds_total{image!=\"\",namespace=~\"$namespace\",pod_name=~\".*-kafka-sts-$kafka\",container_name!=\"POD\"}[2m])) "
      }
     ]
    },
    {
     "title": "CPU for kafka $kafka",
     "type": "graph",
     "description": "Graph showing the CPU usage and limits for each container in kafka pod $kafka",
     "gridPos": { "h": 8, "w": 10, "x": 14, "y": 1 },
     "repeat": "kafka",
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by (container_name)( rate(container_cpu_usage_seconds_total{image!=\"\", namespace=\"$namespace\",container_name!=\"POD\",pod_name=~\".*-kafka-sts-$kafka\"}[2m] ) )",
       "legendFormat": "{{ container_name }}"
      },
      {
       "expr": "kube_pod_container_resource_limits_cpu_cores{namespace=\"$namespace\", pod=~\".*-kafka-sts-$kafka\", container!=\"POD\"}",
       "legendFormat": "Limit: {{ container }}"
      }
     ]
    },
    {
     "title": "Total Memory Usage by $kafka",
     "type": "singlestat",
     "description": "The total memory being used inside Kafka pod $kafka. It is a sum of the memory in use by the containers inside the pod",
     "gridPos": { "h": 8, "w": 3, "x": 0, "y": 9 },
     "format": "bytes",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(container_memory_working_set_bytes{image!=\"\", namespace=~\"$namespace\", pod_name=~\".*-kafka-sts-$kafka\",container_name!=\"POD\"})"
      }
     ]
    },
    {
     "title": "Memory Usage by kafka $kafka",
     "type": "graph",
     "description": "Graph showing the memory usage and limits for each container in kafka pod $kafka",
     "gridPos": { "h": 8, "w": 9, "x": 3, "y": 9 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "avg by(container_name) (container_memory_working_set_bytes{image!=\"\", namespace=\"$namespace\", pod_name=~\".*-kafka-sts-$kafka\", container_name!=\"POD\"})",
       "legendFormat": "Current: {{ container_name }}"
      },
      {
       "expr": "kube_pod_container_resource_limits_memory_bytes{namespace=\"$namespace\", pod=~\".*-kafka-sts-$kafka\", container!=\"POD\"}",
       "legendFormat": "Limit: {{ container }}"
      }
     ]
    },
    {
     "title": "Total CPU for $kafka",
     "type": "singlestat",
     "description": "The total CPU in use by kafka pod $kafka. It is a sum of the CPU usage by the containers inside the pod",
     "gridPos": { "h": 8, "w": 2, "x": 12, "y": 9 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(rate(container_cpu_usage_seconds_total{image!=\"\",namespace=~\"$namespace\",pod_name=~\".*-kafka-sts-$kafka\",container_name!=\"POD\"}[2m])) "
      }
     ]
    },
    {
     "title": "CPU for kafka $kafka",
     "type": "graph",
     "description": "Graph showing the CPU usage and limits for each container in kafka pod $kafka",
     "gridPos": { "h": 8, "w": 10, "x": 14, "y": 9 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by (container_name)( rate(container_cpu_usage_seconds_total{image!=\"\", namespace=\"$namespace\",container_name!=\"POD\",pod_name=~\".*-kafka-sts-$kafka\"}[2m] ) )",
       "legendFormat": "{{ container_name }}"
      },
      {
       "expr": "kube_pod_container_resource_limits_cpu_cores{namespace=\"$namespace\", pod=~\".*-kafka-sts-$kafka\", container!=\"POD\"}",
       "legendFormat": "Limit: {{ container }}"
      }
     ]
    },
    {
     "title": "Total Memory Usage by $kafka",
     "type": "singlestat",
     "description": "The total memory being used inside Kafka pod $kafka. It is a sum of the memory in use by the containers inside the pod",
     "gridPos": { "h": 8, "w": 3, "x": 0, "y": 17 },
     "format": "bytes",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(container_memory_working_set_bytes{image!=\"\", namespace=~\"$namespace\", pod_name=~\".*-kafka-sts-$kafka\",container_name!=\"POD\"})"
      }
     ]
    },
    {
     "title": "Memory Usage by kafka $kafka",
     "type": "graph",
     "description": "Graph showing the memory usage and limits for each container in kafka pod $kafka",
     "gridPos": { "h": 8, "w": 9, "x": 3, "y": 17 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "avg by(container_name) (container_memory_working_set_bytes{image!=\"\", namespace=\"$namespace\", pod_name=~\".*-kafka-sts-$kafka\", container_name!=\"POD\"})",
       "legendFormat": "Current: {{ container_name }}"
      },
      {
       "expr": "kube_pod_container_resource_limits_memory_bytes{namespace=\"$namespace\", pod=~\".*-kafka-sts-$kafka\", container!=\"POD\"}",
       "legendFormat": "Limit: {{ container }}"
      }
     ]
    },
    {
     "title": "Total CPU for $kafka",
     "type": "singlestat",
     "description": "The total CPU in use by kafka pod $kafka. It is a sum of the CPU usage by the containers inside the pod",
     "gridPos": { "h": 8, "w": 2, "x": 12, "y": 17 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(rate(container_cpu_usage_seconds_total{image!=\"\",namespace=~\"$namespace\",pod_name=~\".*-kafka-sts-$kafka\",container_name!=\"POD\"}[2m])) "
      }
     ]
    },
    {
     "title": "CPU for kafka $kafka",
     "type": "graph",
     "description": "Graph showing the CPU usage and limits for each container in kafka pod $kafka",
     "gridPos": { "h": 8, "w": 10, "x": 14, "y": 17 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by (container_name)( rate(container_cpu_usage_seconds_total{image!=\"\", namespace=\"$namespace\",container_name!=\"POD\",pod_name=~\".*-kafka-sts-$kafka\"}[2m] ) )",
       "legendFormat": "{{ container_name }}"
      },
      {
       "expr": "kube_pod_container_resource_limits_cpu_cores{namespace=\"$namespace\", pod=~\".*-kafka-sts-$kafka\", container!=\"POD\"}",
       "legendFormat": "Limit: {{ container }}"
      }
     ]
    }
   ]
  },
  {
   "title": "Kafka Throughput",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "Byte rate into pod $kafka",
     "type": "singlestat",
     "description": "The rate of byte transfer into the kafka pod $kafka. This data, does not necessarily go to kafka as there are other containers, but almost all of it will go to kafka",
     "gridPos": { "h": 7, "w": 3, "x": 0, "y": 2 },
     "repeat": "kafka",
     "format": "Bps",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(rate(container_network_receive_bytes_total{namespace=~\"$namespace\",pod_name=~\".*-kafka-sts-$kafka\"}[2m])) "
      }
     ]
    },
    {
     "title": "Byte rate into $kafka - kafka container",
     "type": "singlestat",
     "description": "The rate of byte transfer into the kafka $kafka container. this data does not include kafka to kafka traffic such as replication",
     "gridPos": { "h": 7, "w": 3, "x": 3, "y": 2 },
     "repeat": "kafka",
     "format": "Bps",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(kafka_server_brokertopicmetrics_bytesinpersec_alltopics_oneminuterate{kubernetes_namespace=\"$namespace\", kafka=~\"$kafka\"})"
      }
     ]
    },
    {
     "title": "Byte rate into kafka $kafka",
     "type": "graph",
     "description": "Graph showing the byte rate for data flowing into the kafka pod and container",
     "gridPos": { "h": 7, "w": 6, "x": 6, "y": 2 },
     "repeat": "kafka",
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "rate (container_network_receive_bytes_total{namespace=\"$namespace\", pod_name=~\".*-kafka-sts-$kafka\",interface=\"eth0\"}[2m])",
       "legendFormat": "Byte rate into pod"
      },
      {
       "expr": "kafka_server_brokertopicmetrics_bytesinpersec_alltopics_oneminuterate{namespace=\"$namespace\", kafka=~\"$kafka\"}",
       "legendFormat": "Byte rate into container"
      }
     ]
    },
    {
     "title": "Byte rate out of pod $kafka",
     "type": "singlestat",
     "description": "The rate of byte transfer out of the kafka pod $kafka. this data, does not necessarily come from kafka as there are other containers, but almost all of it will have come from kafka",
     "gridPos": { "h": 7, "w": 3, "x": 12, "y": 2 },
     "repeat": "kafka",
     "format": "Bps",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(rate(container_network_transmit_bytes_total{namespace=~\"$namespace\",pod_name=~\".*-kafka-sts-$kafka\"}[2m]))"
      }
     ]
    },
    {
     "title": "Byte rate out of $kafka - kafka container",
     "type": "singlestat",
     "description": "The rate of byte transfer out of the kafka $kafka container. this data does not include kafka to kafka traffic such as replication",
     "gridPos": { "h": 7, "w": 3, "x": 15, "y": 2 },
     "repeat": "kafka",
     "format": "Bps",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(kafka_server_brokertopicmetrics_bytesoutpersec_alltopics_oneminuterate{kubernetes_namespace=\"$namespace\", kafka=~\"$kafka\"}) "
      }
     ]
    },
    {
     "title": "Byte rate out of kafka pod $kafka",
     "type": "graph",
     "description": "Graph showing the byte rate for data flowing into the kafka pod and container",
     "gridPos": { "h": 7, "w": 6, "x": 18, "y": 2 },
     "repeat": "kafka",
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "rate (container_network_transmit_bytes_total{namespace=\"$namespace\", pod_name=~\".*-kafka-sts-$kafka\",interface=\"eth0\"}[2m])",
       "legendFormat": "Byte rate out of pod"
      },
      {
       "expr": "kafka_server_brokertopicmetrics_bytesoutpersec_alltopics_oneminuterate{namespace=\"$namespace\", kafka=~\"$kafka\"}",
       "legendFormat": "Byte rate out of container"
      }
     ]
    },
    {
     "title": "Byte rate into pod $kafka",
     "type": "singlestat",
     "description": "The rate of byte transfer into the kafka pod $kafka. This data, does not necessarily go to kafka as there are other containers, but almost all of it will go to kafka",
     "gridPos": { "h": 7, "w": 3, "x": 0, "y": 9 },
     "format": "Bps",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(rate(container_network_receive_bytes_total{namespace=~\"$namespace\",pod_name=~\".*-kafka-sts-$kafka\"}[2m])) "
      }
     ]
    },
    {
     "title": "Byte rate into $kafka - kafka container",
     "type": "singlestat",
     "description": "The rate of byte transfer into the kafka $kafka container. this data does not include kafka to kafka traffic such as replication",
     "gridPos": { "h": 7, "w": 3, "x": 3, "y": 9 },
     "format": "Bps",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(kafka_server_brokertopicmetrics_bytesinpersec_alltopics_oneminuterate{kubernetes_namespace=\"$namespace\", kafka=~\"$kafka\"})"
      }
     ]
    },
    {
     "title": "Byte rate into kafka $kafka",
     "type": "graph",
     "description": "Graph showing the byte rate for data flowing into the kafka pod and container",
     "gridPos": { "h": 7, "w": 6, "x": 6, "y": 9 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "rate (container_network_receive_bytes_total{namespace=\"$namespace\", pod_name=~\".*-kafka-sts-$kafka\",interface=\"eth0\"}[2m])",
       "legendFormat": "Byte rate into pod"
      },
      {
       "expr": "kafka_server_brokertopicmetrics_bytesinpersec_alltopics_oneminuterate{namespace=\"$namespace\", kafka=~\"$kafka\"}",
       "legendFormat": "Byte rate into container"
      }
     ]
    },
    {
     "title": "Byte rate out of pod $kafka",
     "type": "singlestat",
     "description": "The rate of byte transfer out of the kafka pod $kafka. this data, does not necessarily come from kafka as there are other containers, but almost all of it will have come from kafka",
     "gridPos": { "h": 7, "w": 3, "x": 12, "y": 9 },
     "format": "Bps",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(rate(container_network_transmit_bytes_total{namespace=~\"$namespace\",pod_name=~\".*-kafka-sts-$kafka\"}[2m]))"
      }
     ]
    },
    {
     "title": "Byte rate out of $kafka - kafka container",
     "type": "singlestat",
     "description": "The rate of byte transfer out of the kafka $kafka container. this data does not include kafka to kafka traffic such as replication",
     "gridPos": { "h": 7, "w": 3, "x": 15, "y": 9 },
     "format": "Bps",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(kafka_server_brokertopicmetrics_bytesoutpersec_alltopics_oneminuterate{kubernetes_namespace=\"$namespace\", kafka=~\"$kafka\"}) "
      }
     ]
    },
    {
     "title": "Byte rate out of kafka pod $kafka",
     "type": "graph",
     "description": "Graph showing the byte rate for data flowing into the kafka pod and container",
     "gridPos": { "h": 7, "w": 6, "x": 18, "y": 9 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "rate (container_network_transmit_bytes_total{namespace=\"$namespace\", pod_name=~\".*-kafka-sts-$kafka\",interface=\"eth0\"}[2m])",
       "legendFormat": "Byte rate out of pod"
      },
      {
       "expr": "kafka_server_brokertopicmetrics_bytesoutpersec_alltopics_oneminuterate{namespace=\"$namespace\", kafka=~\"$kafka\"}",
       "legendFormat": "Byte rate out of container"
      }
     ]
    },
    {
     "title": "Byte rate into pod $kafka",
     "type": "singlestat",
     "description": "The rate of byte transfer into the kafka pod $kafka. This data, does not necessarily go to kafka as there are other containers, but almost all of it will go to kafka",
     "gridPos": { "h": 7, "w": 3, "x": 0, "y": 16 },
     "format": "Bps",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(rate(container_network_receive_bytes_total{namespace=~\"$namespace\",pod_name=~\".*-kafka-sts-$kafka\"}[2m])) "
      }
     ]
    },
    {
     "title": "Byte rate into $kafka - kafka container",
     "type": "singlestat",
     "description": "The rate of byte transfer into the kafka $kafka container. this data does not include kafka to kafka traffic such as replication",
     "gridPos": { "h": 7, "w": 3, "x": 3, "y": 16 },
     "format": "Bps",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(kafka_server_brokertopicmetrics_bytesinpersec_alltopics_oneminuterate{kubernetes_namespace=\"$namespace\", kafka=~\"$kafka\"})"
      }
     ]
    },
    {
     "title": "Byte rate into kafka $kafka",
     "type": "graph",
     "description": "Graph showing the byte rate for data flowing into the kafka pod and container",
     "gridPos": { "h": 7, "w": 6, "x": 6, "y": 16 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "rate (container_network_receive_bytes_total{namespace=\"$namespace\", pod_name=~\".*-kafka-sts-$kafka\",interface=\"eth0\"}[2m])",
       "legendFormat": "Byte rate into pod"
      },
      {
       "expr": "kafka_server_brokertopicmetrics_bytesinpersec_alltopics_oneminuterate{namespace=\"$namespace\", kafka=~\"$kafka\"}",
       "legendFormat": "Byte rate into container"
      }
     ]
    },
    {
     "title": "Byte rate out of pod $kafka",
     "type": "singlestat",
     "description": "The rate of byte transfer out of the kafka pod $kafka. this data, does not necessarily come from kafka as there are other containers, but almost all of it will have come from kafka",
     "gridPos": { "h": 7, "w": 3, "x": 12, "y": 16 },
     "format": "Bps",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(rate(container_network_transmit_bytes_total{namespace=~\"$namespace\",pod_name=~\".*-kafka-sts-$kafka\"}[2m]))"
      }
     ]
    },
    {
     "title": "Byte rate out of $kafka - kafka container",
     "type": "singlestat",
     "description": "The rate of byte transfer out of the kafka $kafka container. this data does not include kafka to kafka traffic such as replication",
     "gridPos": { "h": 7, "w": 3, "x": 15, "y": 16 },
     "format": "Bps",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(kafka_server_brokertopicmetrics_bytesoutpersec_alltopics_oneminuterate{kubernetes_namespace=\"$namespace\", kafka=~\"$kafka\"}) "
      }
     ]
    },
    {
     "title": "Byte rate out of kafka pod $kafka",
     "type": "graph",
     "description": "Graph showing the byte rate for data flowing into the kafka pod and container",
     "gridPos": { "h": 7, "w": 6, "x": 18, "y": 16 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "rate (container_network_transmit_bytes_total{namespace=\"$namespace\", pod_name=~\".*-kafka-sts-$kafka\",interface=\"eth0\"}[2m])",
       "legendFormat": "Byte rate out of pod"
      },
      {
       "expr": "kafka_server_brokertopicmetrics_bytesoutpersec_alltopics_oneminuterate{namespace=\"$namespace\", kafka=~\"$kafka\"}",
       "legendFormat": "Byte rate out of container"
      }
     ]
    }
   ]
  },
  {
   "title": "Kafka Proxy Performance",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU Usage by Proxy $proxy",
     "type": "singlestat",
     "description": "The Kafka proxy proxies traffic from clients to the kafka pods. Therefore it is an important part of the message flow. This tracks the CPU usage of Kafka proxy $proxy",
     "gridPos": { "h": 7, "w": 2, "x": 0, "y": 3 },
     "repeat": "proxy",
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(rate(container_cpu_usage_seconds_total{image!=\"\",namespace=~\"$namespace\",pod_name=~\"$proxy\",container_name!=\"POD\"}[2m])) "
      }
     ]
    },
    {
     "title": "CPU for proxy $proxy",
     "type": "graph",
     "description": "The Kafka proxy proxies traffic from clients to the kafka pods. Therefore it is an important part of the message flow. This tracks the CPU usage and limit of Kafka proxy $proxy over time",
     "gridPos": { "h": 7, "w": 6, "x": 2, "y": 3 },
     "repeat": "proxy",
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by (container_name)( rate(container_cpu_usage_seconds_total{namespace=\"$namespace\", image!=\"\",container_name!=\"POD\",pod_name=~\"$proxy\"}[2m] ) )",
       "legendFormat": "{{ container_name }}"
      },
      {
       "expr": "kube_pod_container_resource_limits_cpu_cores{namespace=\"$namespace\", pod=~\"$proxy\", container!=\"POD\"}",
       "legendFormat": "Limit: {{ container }}"
      }
     ]
    },
    {
     "title": "Byte rates for proxy $proxy",
     "type": "graph",
     "description": "The Kafka proxy proxies traffic from clients to the kafka pods. Therefore it is an important part of the message flow. This tracks the byte rate into and our of the kafka proxy",
     "gridPos": { "h": 7, "w": 7, "x": 8, "y": 3 },
     "repeat": "proxy",
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "avg by (pod_name) (rate (container_network_receive_bytes_total{namespace=\"$namespace\", pod_name=~\"$proxy\",interface=\"eth0\"}[2m]))",
       "legendFormat": "RX : {{ pod_name }}"
      },
      {
       "expr": "avg by (pod_name) (rate (container_network_transmit_bytes_total{namespace=\"$namespace\", pod_name=~\"$proxy\",interface=\"eth0\"}[2m]))",
       "legendFormat": "TX : {{ pod_name }}"
      }
     ]
    },
    {
     "title": "Memory usage by edge proxy $proxy",
     "type": "singlestat",
     "description": "The Kafka proxy proxies traffic from clients to the kafka pods. Therefore it is an important part of the message flow. This tracks the Memory usage of Kafka proxy $proxy",
     "gridPos": { "h": 7, "w": 3, "x": 15, "y": 3 },
     "repeat": "proxy",
     "format": "bytes",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(container_memory_working_set_bytes{image!=\"\", namespace=~\"$namespace\", pod_name=~\"$proxy\",container_name!=\"POD\"})"
      }
     ]
    },
    {
     "title": "Memory Usage by edge proxy $proxy",
     "type": "graph",
     "description": "The Kafka proxy proxies traffic from clients to the kafka pods. Therefore it is an important part of the message flow. This tracks the Memory usage and limits of Kafka proxy $proxy",
     "gridPos": { "h": 7, "w": 6, "x": 18, "y": 3 },
     "repeat": "proxy",
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "avg by(container_name) (container_memory_working_set_bytes{namespace=\"$namespace\", image!=\"\", pod_name=~\"$proxy\", container_name!=\"POD\"})",
       "legendFormat": "Current: {{ container_name }}"
      },
      {
       "expr": "kube_pod_container_resource_limits_memory_bytes{namespace=\"$namespace\", pod=~\"$proxy\", container!=\"POD\"}",
       "legendFormat": "Limit: {{ container }}"
      }
     ]
    },
    {
     "title": "CPU Usage by Proxy $proxy",
     "type": "singlestat",
     "description": "The Kafka proxy proxies traffic from clients to the kafka pods. Therefore it is an important part of the message flow. This tracks the CPU usage of Kafka proxy $proxy",
     "gridPos": { "h": 7, "w": 2, "x": 0, "y": 10 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(rate(container_cpu_usage_seconds_total{image!=\"\",namespace=~\"$namespace\",pod_name=~\"$proxy\",container_name!=\"POD\"}[2m])) "
      }
     ]
    },
    {
     "title": "CPU for proxy $proxy",
     "type": "graph",
     "description": "The Kafka proxy proxies traffic from clients to the kafka pods. Therefore it is an important part of the message flow. This tracks the CPU usage and limit of Kafka proxy $proxy over time",
     "gridPos": { "h": 7, "w": 6, "x": 2, "y": 10 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by (container_name)( rate(container_cpu_usage_seconds_total{namespace=\"$namespace\", image!=\"\",container_name!=\"POD\",pod_name=~\"$proxy\"}[2m] ) )",
       "legendFormat": "{{ container_name }}"
      },
      {
       "expr": "kube_pod_container_resource_limits_cpu_cores{namespace=\"$namespace\", pod=~\"$proxy\", container!=\"POD\"}",
       "legendFormat": "Limit: {{ container }}"
      }
     ]
    },
    {
     "title": "Byte rates for proxy $proxy",
     "type": "graph",
     "description": "The Kafka proxy proxies traffic from clients to the kafka pods. Therefore it is an important part of the message flow. This tracks the byte rate into and our of the kafka proxy",
     "gridPos": { "h": 7, "w": 7, "x": 8, "y": 10 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "avg by (pod_name) (rate (container_network_receive_bytes_total{namespace=\"$namespace\", pod_name=~\"$proxy\",interface=\"eth0\"}[2m]))",
       "legendFormat": "RX : {{ pod_name }}"
      },
      {
       "expr": "avg by (pod_name) (rate (container_network_transmit_bytes_total{namespace=\"$namespace\", pod_name=~\"$proxy\",interface=\"eth0\"}[2m]))",
       "legendFormat": "TX : {{ pod_name }}"
      }
     ]
    },
    {
     "title": "Memory usage by edge proxy $proxy",
     "type": "singlestat",
     "description": "The Kafka proxy proxies traffic from clients to the kafka pods. Therefore it is an important part of the message flow. This tracks the Memory usage of Kafka proxy $proxy",
     "gridPos": { "h": 7, "w": 3, "x": 15, "y": 10 },
     "format": "bytes",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(container_memory_working_set_bytes{image!=\"\", namespace=~\"$namespace\", pod_name=~\"$proxy\",container_name!=\"POD\"})"
      }
     ]
    },
    {
     "title": "Memory Usage by edge proxy $proxy",
     "type": "graph",
     "description": "The Kafka proxy proxies traffic from clients to the kafka pods. Therefore it is an important part of the message flow. This tracks the Memory usage and limits of Kafka proxy $proxy",
     "gridPos": { "h": 7, "w": 6, "x": 18, "y": 10 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "avg by(container_name) (container_memory_working_set_bytes{namespace=\"$namespace\", image!=\"\", pod_name=~\"$proxy\", container_name!=\"POD\"})",
       "legendFormat": "Current: {{ container_name }}"
      },
      {
       "expr": "kube_pod_container_resource_limits_memory_bytes{namespace=\"$namespace\", pod=~\"$proxy\", container!=\"POD\"}",
       "legendFormat": "Limit: {{ container }}"
      }
     ]
    },
    {
     "title": "CPU Usage by Proxy $proxy",
     "type": "singlestat",
     "description": "The Kafka proxy proxies traffic from clients to the kafka pods. Therefore it is an important part of the message flow. This tracks the CPU usage of Kafka proxy $proxy",
     "gridPos": { "h": 7, "w": 2, "x": 0, "y": 17 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(rate(container_cpu_usage_seconds_total{image!=\"\",namespace=~\"$namespace\",pod_name=~\"$proxy\",container_name!=\"POD\"}[2m])) "
      }
     ]
    },
    {
     "title": "CPU for proxy $proxy",
     "type": "graph",
     "description": "The Kafka proxy proxies traffic from clients to the kafka pods. Therefore it is an important part of the message flow. This tracks the CPU usage and limit of Kafka proxy $proxy over time",
     "gridPos": { "h": 7, "w": 6, "x": 2, "y": 17 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by (container_name)( rate(container_cpu_usage_seconds_total{namespace=\"$namespace\", image!=\"\",container_name!=\"POD\",pod_name=~\"$proxy\"}[2m] ) )",
       "legendFormat": "{{ container_name }}"
      },
      {
       "expr": "kube_pod_container_resource_limits_cpu_cores{namespace=\"$namespace\", pod=~\"$proxy\", container!=\"POD\"}",
       "legendFormat": "Limit: {{ container }}"
      }
     ]
    },
    {
     "title": "Byte rates for proxy $proxy",
     "type": "graph",
     "description": "The Kafka proxy proxies traffic from clients to the kafka pods. Therefore it is an important part of the message flow. This tracks the byte rate into and our of the kafka proxy",
     "gridPos": { "h": 7, "w": 7, "x": 8, "y": 17 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "avg by (pod_name) (rate (container_network_receive_bytes_total{namespace=\"$namespace\", pod_name=~\"$proxy\",interface=\"eth0\"}[2m]))",
       "legendFormat": "RX : {{ pod_name }}"
      },
      {
       "expr": "avg by (pod_name) (rate (container_network_transmit_bytes_total{namespace=\"$namespace\", pod_name=~\"$proxy\",interface=\"eth0\"}[2m]))",
       "legendFormat": "TX : {{ pod_name }}"
      }
     ]
    },
    {
     "title": "Memory usage by edge proxy $proxy",
     "type": "singlestat",
     "description": "The Kafka proxy proxies traffic from clients to the kafka pods. Therefore it is an important part of the message flow. This tracks the Memory usage of Kafka proxy $proxy",
     "gridPos": { "h": 7, "w": 3, "x": 15, "y": 17 },
     "format": "bytes",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(container_memory_working_set_bytes{image!=\"\", namespace=~\"$namespace\", pod_name=~\"$proxy\",container_name!=\"POD\"})"
      }
     ]
    },
    {
     "title": "Memory Usage by edge proxy $proxy",
     "type": "graph",
     "description": "The Kafka proxy proxies traffic from clients to the kafka pods. Therefore it is an important part of the message flow. This tracks the Memory usage and limits of Kafka proxy $proxy",
     "gridPos": { "h": 7, "w": 6, "x": 18, "y": 17 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "avg by(container_name) (container_memory_working_set_bytes{namespace=\"$namespace\", image!=\"\", pod_name=~\"$proxy\", container_name!=\"POD\"})",
       "legendFormat": "Current: {{ container_name }}"
      },
      {
       "expr": "kube_pod_container_resource_limits_memory_bytes{namespace=\"$namespace\", pod=~\"$proxy\", container!=\"POD\"}",
       "legendFormat": "Limit: {{ container }}"
      }
     ]
    }
   ]
  },
  { "title": "Collector Performance", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 } },
  {
   "title": "CPU for Collector $collector",
   "type": "singlestat",
   "description": "The collector collects metrics data on messages flowing through the system. Looking at all this data may end up having a performance impact. This tracks the total CPU usage of the collector as a sum of the containers",
   "gridPos": { "h": 7, "w": 2, "x": 0, "y": 4 },
   "repeat": "collector",
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{image!=\"\",namespace=~\"$namespace\",pod_name=~\"$collector\",container_name!=\"POD\"}[2m])) "
    }
   ]
  },
  {
   "title": "CPU for Collector $collector",
   "type": "graph",
   "description": "The collector collects metrics data on messages flowing through the system. Looking at all this data may end up having a performance impact. This tracks the CPU of the collector",
   "gridPos": { "h": 7, "w": 6, "x": 2, "y": 4 },
   "repeat": "collector",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (container_name)( rate(container_cpu_usage_seconds_total{namespace=\"$namespace\", image!=\"\",container_name!=\"POD\",pod_name=~\"$collector\"}[2m] ) )",
     "legendFormat": "{{ container_name }}"
    },
    {
     "expr": "kube_pod_container_resource_limits_cpu_cores{namespace=\"$namespace\", pod=~\"$collector\", container!=\"POD\"}",
     "legendFormat": "Limit: {{ container }}"
    }
   ]
  },
  {
   "title": "Byte rates for collector $collector",
   "type": "graph",
   "description": "The collector collects metrics data on messages flowing through the system. Looking at all this data may end up having a performance impact. This tracks the byte rate into and out of the collector",
   "gridPos": { "h": 7, "w": 7, "x": 8, "y": 4 },
   "repeat": "collector",
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "rate (container_network_receive_bytes_total{namespace=\"$namespace\", pod_name=~\"$collector\",interface=\"eth0\"}[2m])",
     "legendFormat": "RX : {{ pod_name }}"
    },
    {
     "expr": "rate (container_network_transmit_bytes_total{namespace=\"$namespace\", pod_name=~\"$collector\",interface=\"eth0\"}[2m])",
     "legendFormat": "TX : {{ pod_name }}"
    }
   ]
  },
  {
   "title": "Memory usage by collector $collector",
   "type": "singlestat",
   "description": "The collector collects metrics data on messages flowing through the system. Looking at all this data may end up having a performance impact. This tracks the total memory usage of the collector",
   "gridPos": { "h": 7, "w": 3, "x": 15, "y": 4 },
   "repeat": "collector",
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{image!=\"\", namespace=~\"$namespace\", pod_name=~\"$collector\",container_name!=\"POD\"})"
    }
   ]
  },
  {
   "title": "Memory Usage by collector $collector",
   "type": "graph",
   "description": "The collector collects metrics data on messages flowing through the system. Looking at all this data may end up having a performance impact. This tracks the memory usage of the collectors containers",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 4 },
   "repeat": "collector",
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "avg by(container_name) (container_memory_working_set_bytes{namespace=\"$namespace\", image!=\"\", pod_name=~\"$collector\", container_name!=\"POD\"})",
     "legendFormat": "Current: {{ container_name }}"
    },
    {
     "expr": "kube_pod_container_resource_limits_memory_bytes{namespace=\"$namespace\", pod=~\"$collector\", container!=\"POD\"}",
     "legendFormat": "Limit: {{ container }}"
    }
   ]
  },
  { "title": "Access Controller Performance", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 } },
  {
   "title": "CPU Usage by Access Controller $accessController",
   "type": "singlestat",
   "description": "This tracks the CPU usage of access controller  $accessController",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 12 },
   "repeat": "accessController",
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{image!=\"\",namespace=~\"$namespace\",pod_name=~\"$accessController\",container_name!=\"POD\"}[2m])) "
    }
   ]
  },
  {
   "title": "CPU for Access Controller $accessController",
   "type": "graph",
   "description": "This tracks the CPU usage and limit of Access Controller $accessController over time",
   "gridPos": { "h": 8, "w": 7, "x": 4, "y": 12 },
   "repeat": "accessController",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (container_name)( rate(container_cpu_usage_seconds_total{namespace=\"$namespace\", image!=\"\",container_name!=\"POD\",pod_name=~\"$accessController\"}[2m] ) )",
     "legendFormat": "{{ container_name }}"
    },
    {
     "expr": "kube_pod_container_resource_limits_cpu_cores{namespace=\"$namespace\", pod=~\"$accessController\", container!=\"POD\"}",
     "legendFormat": "Limit: {{ container }}"
    }
   ]
  },
  {
   "title": "Memory usage by Access Controller $accessController",
   "type": "singlestat",
   "description": "Access Controller is ensures that users have to be authorized to access Kafka and the Event Streams components. Looking at all this data may end up having a performance impact. This tracks the total memory usage of the AccessController",
   "gridPos": { "h": 8, "w": 5, "x": 11, "y": 12 },
   "repeat": "accessController",
   "format": "decbytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{image!=\"\", namespace=~\"$namespace\", pod_name=~\"$accessController\",container_name!=\"POD\"})"
    }
   ]
  },
  {
   "title": "Memory Usage by Access Controller $accessController",
   "type": "graph",
   "description": "Access Controller is ensures that users have to be authorized to access Kafka and the Event Streams components. Therefore it is an important part of the message flow. This tracks the Memory usage and limits of Access Controller $accessController",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 12 },
   "repeat": "accessController",
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "avg by(container_name) (container_memory_working_set_bytes{namespace=\"$namespace\", image!=\"\", pod_name=~\"$accessController\", container_name!=\"POD\"})",
     "legendFormat": "Current: {{ container_name }}"
    },
    {
     "expr": "kube_pod_container_resource_limits_memory_bytes{namespace=\"$namespace\", pod=~\"$accessController\", container!=\"POD\"}"
    }
   ]
  }
 ]
}