/*
 * (C) Copyright IBM Corp. 2020, 2021
 *
 * SPDX-License-Identifier: Apache-2.0
 */

package com.ibm.fhir.bucket.persistence;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;

import com.ibm.fhir.database.utils.api.IDatabaseSupplier;
import com.ibm.fhir.database.utils.api.IDatabaseTranslator;
import com.ibm.fhir.database.utils.common.DataDefinitionUtil;
import com.ibm.fhir.database.utils.model.DbType;

/**
 * DAO to encapsulate all the SQL/DML used to retrieve and persist data
 * in the schema
 */
public class AddBucketPath implements IDatabaseSupplier<Long> {
    private static final Logger logger = Logger.getLogger(RegisterLoaderInstance.class.getName());

    // The name of the schema holding the FHIRBUCKET tables
    private final String schemaName;

    // The name of the bucket
    private final String bucketName;

    // The path in which the item resides...basically the key up and including the last /
    private final String bucketPath;


    /**
     * Public constructor
     * @param schemaName
     * @param bucketName
     * @param bucketPath
     */
    public AddBucketPath(String schemaName, String bucketName, String bucketPath) {
        this.schemaName = schemaName;
        this.bucketName = bucketName;
        this.bucketPath = bucketPath;
    }

    @Override
    public Long run(IDatabaseTranslator translator, Connection c) {
        Long bucketPathId;

        // MERGE and upsert-like tricks don't appear to work with Derby
        // when using autogenerated identity columns. So we have to
        // try the old-fashioned way and handle duplicate key
        final String bucketPaths = DataDefinitionUtil.getQualifiedName(schemaName, "bucket_paths");
        final String dml;
        if (translator.getType() == DbType.POSTGRESQL) {
            // For POSTGRES, if a statement fails it causes the whole transaction
            // to fail, so we need turn this into an UPSERT
            dml = "INSERT INTO " + bucketPaths + "(bucket_name, bucket_path) VALUES (?,?) ON CONFLICT(bucket_name, bucket_path) DO NOTHING";
        } else {
            dml = "INSERT INTO " + bucketPaths + "(bucket_name, bucket_path) VALUES (?,?)";
        }

        try (PreparedStatement ps = c.prepareStatement(dml, Statement.RETURN_GENERATED_KEYS)) {
            ps.setString(1, bucketName);
            ps.setString(2, bucketPath);
            ps.executeUpdate();
            ResultSet rs = ps.getGeneratedKeys();
            if (rs != null && rs.next()) {
                bucketPathId = rs.getLong(1);
            } else {
                bucketPathId = null; // postgres on conflict do nothing: record already exists
            }
        } catch (SQLException x) {
            if (translator.isDuplicate(x)) {
                bucketPathId = null; // select it later
            } else {
                // log this, but don't propagate values in the exception
                logger.log(Level.SEVERE, "Error registering bucket: " + dml + "; "
                    + bucketName);
                throw translator.translate(x);
            }
        }

        // If we didn't create a new record, fetch the id of the existing record (we don't delete these
        // records, so no chance of a race condition
        if (bucketPathId == null) {
            final String SQL = "SELECT bucket_path_id FROM " + bucketPaths + " WHERE bucket_name = ? AND bucket_path = ?";
            try (PreparedStatement ps = c.prepareStatement(SQL)) {
                ps.setString(1, bucketName);
                ps.setString(2, bucketPath);
                ResultSet rs = ps.executeQuery();
                if (rs.next()) {
                    bucketPathId = rs.getLong(1);
                }
            } catch (SQLException x) {
                // log this, but don't propagate values in the exception
                logger.log(Level.SEVERE, "Error getting bucket path: " + SQL + "; "
                    + bucketName);
                throw translator.translate(x);
            }
        }

        return bucketPathId;
    }
}