#!/usr/bin/env bash
###############################################################################
# (C) Copyright IBM Corp. 2016, 2017, 2019
#
# SPDX-License-Identifier: Apache-2.0
###############################################################################

# Determine the location of this script.
dirname=`dirname "$0"`
basedir=`unset CDPATH; cd $dirname && pwd`

# build classpath from all jars in lib
CP_SEP=":"
CP=.
for i in $basedir/lib/*.jar; do
    CP="${CP}${CP_SEP}${i}"
done

# add any JVM options here
#JAVA_OPTS=""

java -cp "${CP}" ${JAVA_OPTS} com.ibm.watson.health.fhir.cli.FHIRCLI ${1+"$@"}
