# ----------------------------------------------------------------------------
# (C) Copyright IBM Corp. 2020
#
# SPDX-License-Identifier: Apache-2.0
# ----------------------------------------------------------------------------

FROM ibmcom/ibm-fhir-server:4.4.0

CMD ["/opt/ol/wlp/bin/server", "run", "fhir-server"]
